version: '3.8'

services:
  # Main API service
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/grammar.db
      - MODEL_NAME=vennify/t5-base-grammar-correction
      - DEVICE=cpu
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service with hot reload
  dev:
    build: .
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/grammar.db
      - MODEL_NAME=vennify/t5-base-grammar-correction
      - DEVICE=cpu
      - RELOAD=true
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    command: ["uvicorn", "src.grammar_app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    profiles:
      - dev

  # Testing service
  test:
    build: .
    environment:
      - DATABASE_URL=sqlite:///./test_grammar.db
      - MODEL_NAME=vennify/t5-base-grammar-correction
      - DEVICE=cpu
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
    command: ["pytest", "tests/", "-v", "--cov=src"]
    profiles:
      - test

  # Documentation service
  docs:
    build: .
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/grammar.db
      - MODEL_NAME=vennify/t5-base-grammar-correction
      - DEVICE=cpu
    volumes:
      - ./docs:/app/docs
    command: ["mkdocs", "serve", "-a", "0.0.0.0:8000"]
    profiles:
      - docs

volumes:
  data:
  models:
  logs:
